### ISSUE TITLE
Monitor Akka actors with Prometheus + Kamon

### ISSUE THREAD

**Issue by felipegutierrez** [felipegutierrez/explore-akka#8]
How to monitor Akka actors and export metrics to Prometheus? There is one possible solution using [Exposing Metrics for Prometheus with Kamon](https://kamon.io/docs/latest/reporters/prometheus/) but I couldn't do yet and I have [this question on stackoverflow](https://stackoverflow.com/q/65345599/2096986).

**Comment by felipegutierrez** [comment]
I had to configure Prometheus to scrape the Kamon web service through the config file

```
cat /etc/prometheus/prometheus.yml 
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "kamon"
    scrape_interval: "5s"
    static_configs:
      - targets: ['localhost:9095']
    metrics_path: /
```
add these 2 Kamon libraries at `build.sbt`:
```
  "io.kamon" %% "kamon-bundle" % kamonVersion,
  "io.kamon" %% "kamon-prometheus" % kamonVersion,
```
add this configuration at `application.conf`:
```
kamon.instrumentation.akka.filters {
  actors.track {
    includes = [ "AkkaQuickStart/user/*" ]
    # excludes = [ "AkkaQuickStart/system/**" ]
  }
}
```
Start Kamon and call the counter:
```
Kamon.init()
val counterSendMsg = Kamon.counter("counter-send-msg")
counterSendMsg.withTag("whom", message.whom).increment()
```
